--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CosmicDevTeam/HomeSystem
build-by-default: true
branches:
- main
projects:
  HomeSystem:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 4.6.5
        branch: "pm5"
      - src: jojoe77777/FormAPI/SimpleForm
...
